### ISSUE TITLE
Automatically capture Monte Carlo error, possibly as part of summary()

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/SimEngine#14]
Not sure if this is possible but it may be in some cases - need to check Monte Carlo literature

**Comment by Avi-Kenny** [comment]
Formulas given in Table 6 of https://onlinelibrary.wiley.com/doi/full/10.1002/sim.8086

**Comment by cwolock** [comment]
This has been implemented for all inferential summaries.
