### ISSUE TITLE
new.sim as Generic Function

### ISSUE THREAD

**Issue by discoleo** [Avi-Kenny/SimEngine#82]
# Function new_sim

R defines 2 generic functions "new" (although there is also a simple "new" function). It makes sense to rename the new_sim function as new.sim.

## Searching Generic Functions

R offers a nice functionality to search for generic functions, which is very practical when working with multiple packages:
> methods(new)
> \# will find/list the functions "new" in all loaded packages;

Note:
- other functions may also benefit from a generic naming scheme (including in many other packages);

**Comment by Avi-Kenny** [comment]
Hi, @discoleo! Thanks for downloading the package and for the suggestion. We did consider a generic naming scheme at one point and debated the pros and cons of this. We ultimately decided to not do this for several reasons. The main reason is that we want users to be able to directly access the documentation with a single command, i.e. `?new_sim`. Also, in this case, the interface of the R generic `new` function is different than the interface of the `new_sim` function, as the former takes in a single argument and the latter takes no arguments. We realize that this choice is not optimal for all users.

**Comment by discoleo** [comment]
*Minor Clarification*

- Function **new**: is not generic;
- Functions new.env & new.packages: mimic a generic function and can be searched using methods(new);

> methods(new)
> \# [1] new.env      new.packages
> args(new.env)
> \# function (hash = TRUE, parent = parent.frame(), size = 29L)

A big advantage of the "generic"-naming scheme is the ability to quickly search for specific functions: e.g. methods(new), methods(plot) - which is particularly useful when working with several packages at once. Unfortunately many packages do not understand these benefits.

Users can still use the full function name: in this case it would be actually necessary to use the exact function name (e.g. new.sim), as the function "new" is not a generic function per se. The advantage is indirect, by enabling R's mechanism of "generic" searches.
