### ISSUE TITLE
 'relocate' is not an exported object from 'namespace:dplyr'

### ISSUE THREAD

**Issue by nhavt** [Avi-Kenny/SimEngine#85]
Hi Avi-Kenny,

when i tried the following codes, I got an error message, see below
```
  sim <- new_sim()
  sim %<>% set_levels(n=c(20,40,60,80))
  sim %<>% set_config(num_sim=1000)
  # Error: 'relocate' is not an exported object from 'namespace:dplyr'
````
Do you have any idea how to fix it? Perhaps, I did something wrong. Thank you. Nha

**Comment by Avi-Kenny** [comment]
Hi! Can you try updating the `dplyr` package, and then rerunning this code?
You can do this using `install.packages("dplyr")`. Let us know if this does
not fix your problem.
