### ISSUE TITLE
Error in loadNamespace(x) : there is no package called ‘pbapply’

### ISSUE THREAD

**Issue by grahamammal** [Avi-Kenny/SimEngine#91]
When I run SimEngine on a fresh installation of R, I get this error message when calling run(). You may have forgotten to add pbapply to the dependencies for SimEngine? I used the CRAN download.

**Comment by Avi-Kenny** [comment]
Thanks for flagging this. The `pbapply` package is listed in the "Imports" section of the `DESCRIPTION` file, so I'm not totally sure why this is happening. Did you install SimEngine with `install.packages(..., dependencies=TRUE)`?

**Comment by grahamammal** [comment]
Hi Avi. When I install using that command pbapply is also installed, but not when I call install.packages("SimEngine"), which is what I do for all other packages. Also, the progress bar, which is what I assume pbapply is for, doesn't work on this version of SimEngine for me. It jumps straight from 0% to 100% everytime. I haven't used SimEngine in a couple months but last time I used it I didn't have this problem. I'm on R 4.3.1 if that is relevant.

**Comment by Avi-Kenny** [comment]
The progress bar bug is a known issue that occurs only when running in parallel; hopefully we can fix this soon (see Issue #83).

After further offline discussion, I am closing this issue, as we think it was a one-time bug and is not a SimEngine issue.
